-- MySQL Script generated by MySQL Workbench
-- Tue Apr  7 08:16:11 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USUARIO` (
  `ID_USUARIO` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `rol` ENUM("administrador", "agente") NOT NULL,
  `fecha_registro` DATE NOT NULL,
  PRIMARY KEY (`ID_USUARIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTES` (
  `ID_CLIENTES` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `fecha_registro` DATE NOT NULL,
  PRIMARY KEY (`ID_CLIENTES`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROPIEDADES_EN_VENTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PROPIEDADES_EN_VENTA` (
  `ID_PROPIEDAD` INT NOT NULL,
  `Titulo` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Precio` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Ciudad` VARCHAR(45) NOT NULL,
  `ID_USUARIO` INT NOT NULL,
  `Fecha_publicacion` DATE NOT NULL,
  PRIMARY KEY (`ID_PROPIEDAD`),
  INDEX `ID_USUARIO_idx` (`ID_USUARIO` ASC) VISIBLE,
  CONSTRAINT `ID_USUARIO`
    FOREIGN KEY (`ID_USUARIO`)
    REFERENCES `mydb`.`USUARIO` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROPIEDADES_EN_ARRIENDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PROPIEDADES_EN_ARRIENDO` (
  `ID_PROPIEDAD` INT NOT NULL,
  `Titulo` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Precio_mensual` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Ciudad` VARCHAR(45) NOT NULL,
  `ID_USUARIO` INT NOT NULL,
  `Fecha_publicacion` DATE NOT NULL,
  PRIMARY KEY (`ID_PROPIEDAD`),
  INDEX `ID_USUARIO_idx` (`ID_USUARIO` ASC) VISIBLE,
  CONSTRAINT `ID_USUARIO`
    FOREIGN KEY (`ID_USUARIO`)
    REFERENCES `mydb`.`USUARIO` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`IMÁGENES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`IMÁGENES` (
  `ID_IMÁGEN` INT NOT NULL,
  `URL_imagen` VARCHAR(255) NOT NULL,
  `ID_PROPIEDAD` INT NOT NULL,
  `Tipo_propiedad` ENUM("venta", "arriendo") NOT NULL,
  PRIMARY KEY (`ID_IMÁGEN`),
  INDEX `ID_PROPIEDAD_idx` (`ID_PROPIEDAD` ASC) VISIBLE,
  CONSTRAINT `ID_PROPIEDAD`
    FOREIGN KEY (`ID_PROPIEDAD`)
    REFERENCES `mydb`.`PROPIEDADES_EN_VENTA` (`ID_PROPIEDAD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_PROPIEDAD`
    FOREIGN KEY (`ID_PROPIEDAD`)
    REFERENCES `mydb`.`PROPIEDADES_EN_ARRIENDO` (`ID_PROPIEDAD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SOLICITUDES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SOLICITUDES` (
  `ID_SOLICITUD` INT NOT NULL,
  `mensaje` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `ID_CLIENTES` INT NOT NULL,
  `ID_PROPIEDAD` INT NOT NULL,
  `tipo_propiedad` ENUM("venta", "arriendo") NOT NULL,
  PRIMARY KEY (`ID_SOLICITUD`),
  INDEX `ID_CLIENTES_idx` (`ID_CLIENTES` ASC) VISIBLE,
  INDEX `ID_PROPIEDAD_idx` (`ID_PROPIEDAD` ASC) VISIBLE,
  CONSTRAINT `ID_CLIENTES`
    FOREIGN KEY (`ID_CLIENTES`)
    REFERENCES `mydb`.`CLIENTES` (`ID_CLIENTES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_PROPIEDAD`
    FOREIGN KEY (`ID_PROPIEDAD`)
    REFERENCES `mydb`.`PROPIEDADES_EN_ARRIENDO` (`ID_PROPIEDAD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_PROPIEDAD`
    FOREIGN KEY (`ID_PROPIEDAD`)
    REFERENCES `mydb`.`PROPIEDADES_EN_VENTA` (`ID_PROPIEDAD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
